import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const src = fs.readFileSync('supabase/functions/spotter/app.ts','utf8');
const fn = name => {
  const start = src.indexOf('  function '+name+'(');
  const end = src.indexOf('\n  }', start)+4;
  assert(start >= 0 && end > start);
  return src.slice(start,end);
};
let buzz=[], now=10000, done=0, drawn=[];
const ctx=vm.createContext({BUZZ:{tap:8,done:[35,55,35]},state:{haptics:true},native:{haptic:k=>buzz.push(k)},navigator:{vibrate:k=>buzz.push(k)}, Date:{now:()=>now},restUntil:12000,restHeld:0,restCued:4,doneRest:()=>{done++;ctx.restUntil=0;},drawRest:x=>drawn.push(x),beep:()=>{}});
vm.runInContext(fn('haptic')+fn('tickRest'),ctx);
vm.runInContext('haptic("tap")',ctx); assert.deepEqual(buzz,['tap']);
ctx.state.haptics=false; vm.runInContext('haptic("done")',ctx);assert.equal(buzz.length,1);
ctx.state.haptics=true;ctx.native=null;vm.runInContext('haptic("tap")',ctx);assert.equal(buzz[1],8);
delete ctx.navigator.vibrate;vm.runInContext('haptic("tap")',ctx);
vm.runInContext('tickRest()',ctx);assert.equal(drawn[0],2000);
now+=60000;vm.runInContext('tickRest();tickRest()',ctx);assert.equal(done,1);
ctx.restUntil=now+2000;ctx.restHeld=1500;now+=100000;vm.runInContext('tickRest()',ctx);assert.equal(done,1);
const config=JSON.parse(fs.readFileSync('capacitor.config.json'));
assert.equal(config.server,undefined);
const html=fs.readFileSync('native-dist/index.html','utf8');
assert(!/<script[^>]+src="https:/.test(html));
assert(html.includes('src="native.js"'));
assert(fs.existsSync('native-dist/assets/pumpy'));
assert(src.includes('if (!native && "serviceWorker" in navigator)'));
console.log('PASS native/web haptics preference gate, missing hardware fallback, rest deadline after suspension, exactly-once completion, paused rest, packaged shell, no remote runtime scripts, native SW guard.');
let draftWrites = 0;
const draft = vm.createContext({ wo: { finished: true, workout: {id:'fixture',title:'fixture'}, entries: [], startedAt: '2026-09-07', i: 0, rounds: {} }, restUntil: 0, native: null, localStorage: { setItem: () => { draftWrites++; } } });
draft.draftKey = () => 'draft';
vm.runInContext(fn('saveDraft') + '; saveDraft();', draft);
assert.equal(draftWrites, 0);
draft.wo.finished = false;
vm.runInContext('saveDraft()', draft);
assert.equal(draftWrites, 1);
console.log('PASS completed workouts cannot be resurrected by background draft saves.');
