-- Spotter — controlled exercise catalog.
--
-- GENERATED FILE. Source of truth is supabase/functions/spotter/catalog.ts;
-- regenerate with: node tools/gen-catalog-migration.mjs
--
-- Reference data, not user data. Every signed-in user may read it; only the
-- service role writes it. The seed upserts on id, so re-running is safe and
-- never removes a row a saved workout might already point at.

create table if not exists public.exercise_catalog (
  id text primary key,
  display_name text not null,
  aliases text[] not null default '{}',
  muscle_groups text[] not null default '{}',
  equipment text[] not null default '{}',
  unilateral boolean not null default false,
  updated_at timestamptz not null default now(),
  constraint catalog_id_slug check (id ~ '^[a-z0-9-]+$'),
  -- keep the catalog inside the vocabularies index.ts already ships, so derived
  -- values always survive pickFrom() and match what the UI renders
  constraint catalog_muscles_known check (muscle_groups <@ array['chest','back','shoulders','biceps','triceps','forearms','core','glutes','quads','hamstrings','calves','full body']::text[]),
  constraint catalog_equipment_known check (equipment <@ array['dumbbells','barbell','kettlebell','resistance bands','pull-up bar','bench','cables','machine','medicine ball','jump rope','box','other']::text[])
);

create index if not exists exercise_catalog_aliases on public.exercise_catalog using gin (aliases);

alter table public.exercise_catalog enable row level security;

do $$ begin
  create policy "catalog readable" on public.exercise_catalog for select to authenticated using (true);
exception when duplicate_object then null; end $$;

insert into public.exercise_catalog (id, display_name, aliases, muscle_groups, equipment, unilateral) values
  ('back-squat', 'Back Squat', array['squat','squats','barbell squat','bb squat','barbell back squat','back squats','high bar squat','low bar squat']::text[], array['quads','glutes','hamstrings','core']::text[], array['barbell']::text[], false),
  ('front-squat', 'Front Squat', array['front squats','barbell front squat','bb front squat']::text[], array['quads','glutes','core']::text[], array['barbell']::text[], false),
  ('goblet-squat', 'Goblet Squat', array['goblet squats','goblets','db goblet squat','dumbbell goblet squat','kb goblet squat','kettlebell goblet squat']::text[], array['quads','glutes','core']::text[], array['dumbbells','kettlebell']::text[], false),
  ('bodyweight-squat', 'Bodyweight Squat', array['air squat','air squats','bw squat','body weight squat','prisoner squat']::text[], array['quads','glutes']::text[], '{}'::text[], false),
  ('jump-squat', 'Jump Squat', array['jump squats','squat jump','squat jumps','jumping squat']::text[], array['quads','glutes','calves']::text[], '{}'::text[], false),
  ('sumo-squat', 'Sumo Squat', array['sumo squats','wide stance squat','plie squat']::text[], array['quads','glutes']::text[], array['dumbbells','kettlebell']::text[], false),
  ('split-squat', 'Split Squat', array['split squats','static lunge','stationary lunge','split stance lunge','split stance squat']::text[], array['quads','glutes']::text[], '{}'::text[], true),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', array['bulgarians','bulgarian','bulgarian squat','bulgarian lunge','bulgarian split squats','bss','rear foot elevated split squat','rfe split squat','rear foot elevated lunge','elevated split squat']::text[], array['quads','glutes','hamstrings']::text[], array['bench']::text[], true),
  ('pistol-squat', 'Pistol Squat', array['pistol squats','single leg squat','one legged squat']::text[], array['quads','glutes','core']::text[], '{}'::text[], true),
  ('cossack-squat', 'Cossack Squat', array['cossack squats','lateral squat','side squat']::text[], array['quads','glutes','hamstrings']::text[], '{}'::text[], true),
  ('box-squat', 'Box Squat', array['box squats']::text[], array['quads','glutes']::text[], array['barbell','box']::text[], false),
  ('overhead-squat', 'Overhead Squat', array['overhead squats','ohs']::text[], array['quads','glutes','shoulders','core']::text[], array['barbell']::text[], false),
  ('zercher-squat', 'Zercher Squat', array['zercher squats']::text[], array['quads','glutes','core']::text[], array['barbell']::text[], false),
  ('hack-squat', 'Hack Squat', array['hack squats','machine hack squat']::text[], array['quads','glutes']::text[], array['machine']::text[], false),
  ('sissy-squat', 'Sissy Squat', array['sissy squats']::text[], array['quads']::text[], '{}'::text[], false),
  ('wall-sit', 'Wall Sit', array['wall sits','wall squat','wall hold']::text[], array['quads','glutes']::text[], '{}'::text[], false),
  ('leg-press', 'Leg Press', array['leg presses','machine leg press']::text[], array['quads','glutes','hamstrings']::text[], array['machine']::text[], false),
  ('leg-extension', 'Leg Extension', array['leg extensions','quad extension','knee extension']::text[], array['quads']::text[], array['machine']::text[], false),
  ('lunge', 'Lunge', array['lunges','forward lunge','front lunge','dumbbell lunge','db lunge','barbell lunge','goblet lunge']::text[], array['quads','glutes','hamstrings']::text[], '{}'::text[], true),
  ('reverse-lunge', 'Reverse Lunge', array['reverse lunges','backward lunge','back lunge','rear lunge']::text[], array['quads','glutes','hamstrings']::text[], '{}'::text[], true),
  ('walking-lunge', 'Walking Lunge', array['walking lunges','travelling lunge','traveling lunge']::text[], array['quads','glutes','hamstrings']::text[], '{}'::text[], true),
  ('lateral-lunge', 'Lateral Lunge', array['lateral lunges','side lunge','side lunges']::text[], array['quads','glutes','hamstrings']::text[], '{}'::text[], true),
  ('curtsy-lunge', 'Curtsy Lunge', array['curtsy lunges','crossover lunge']::text[], array['glutes','quads']::text[], '{}'::text[], true),
  ('step-up', 'Step Up', array['step ups','stepup','stepups','box step up','bench step up']::text[], array['quads','glutes']::text[], array['box']::text[], true),
  ('thruster', 'Thruster', array['thrusters','squat to press','squat press','dumbbell thruster','db thruster','barbell thruster']::text[], array['quads','glutes','shoulders','triceps']::text[], array['dumbbells','barbell']::text[], false),
  ('wall-ball', 'Wall Ball', array['wall balls','wall ball shot','medicine ball thruster']::text[], array['quads','glutes','shoulders']::text[], array['medicine ball']::text[], false),
  ('box-jump', 'Box Jump', array['box jumps','jump to box','box jump over']::text[], array['quads','glutes','calves']::text[], array['box']::text[], false),
  ('broad-jump', 'Broad Jump', array['broad jumps','standing long jump']::text[], array['quads','glutes','calves']::text[], '{}'::text[], false),
  ('skater-jump', 'Skater Jump', array['skater jumps','skaters','skater hops','speed skater','lateral skater']::text[], array['glutes','quads','calves']::text[], '{}'::text[], true),
  ('lateral-bound', 'Lateral Bound', array['lateral bounds','side bound']::text[], array['glutes','quads','calves']::text[], '{}'::text[], true),
  ('tuck-jump', 'Tuck Jump', array['tuck jumps']::text[], array['quads','calves','core']::text[], '{}'::text[], false),
  ('calf-raise', 'Calf Raise', array['calf raises','standing calf raise','heel raise','calve raise']::text[], array['calves']::text[], '{}'::text[], false),
  ('seated-calf-raise', 'Seated Calf Raise', array['seated calf raises']::text[], array['calves']::text[], array['machine']::text[], false),
  ('tibialis-raise', 'Tibialis Raise', array['tib raise','tibialis anterior raise']::text[], array['calves']::text[], '{}'::text[], false),
  ('deadlift', 'Deadlift', array['deadlifts','conventional deadlift','barbell deadlift','bb deadlift','dead lift','dl']::text[], array['back','glutes','hamstrings','forearms']::text[], array['barbell']::text[], false),
  ('sumo-deadlift', 'Sumo Deadlift', array['sumo deadlifts','sumo dl']::text[], array['glutes','quads','back']::text[], array['barbell']::text[], false),
  ('romanian-deadlift', 'Romanian Deadlift', array['romanian deadlifts','rdl','rdls','romanian dead lift','barbell rdl','bb rdl','dumbbell rdl','db rdl']::text[], array['hamstrings','glutes','back']::text[], array['barbell','dumbbells']::text[], false),
  ('single-leg-deadlift', 'Single Leg Deadlift', array['single leg deadlifts','single leg rdl','sl rdl','sldl','one leg deadlift','one legged deadlift','single leg romanian deadlift']::text[], array['hamstrings','glutes','core']::text[], array['dumbbells','kettlebell']::text[], true),
  ('stiff-leg-deadlift', 'Stiff Leg Deadlift', array['stiff legged deadlift','straight leg deadlift']::text[], array['hamstrings','glutes','back']::text[], array['barbell']::text[], false),
  ('trap-bar-deadlift', 'Trap Bar Deadlift', array['hex bar deadlift','trap bar dl']::text[], array['quads','glutes','back','forearms']::text[], array['barbell']::text[], false),
  ('deficit-deadlift', 'Deficit Deadlift', array['deficit deadlifts']::text[], array['back','glutes','hamstrings']::text[], array['barbell']::text[], false),
  ('rack-pull', 'Rack Pull', array['rack pulls','block pull']::text[], array['back','forearms']::text[], array['barbell']::text[], false),
  ('good-morning', 'Good Morning', array['good mornings']::text[], array['hamstrings','glutes','back']::text[], array['barbell']::text[], false),
  ('hip-thrust', 'Hip Thrust', array['hip thrusts','barbell hip thrust','bb hip thrust','glute thrust','hip thruster']::text[], array['glutes','hamstrings']::text[], array['barbell','bench']::text[], false),
  ('glute-bridge', 'Glute Bridge', array['glute bridges','hip bridge','bridge','bridges']::text[], array['glutes','hamstrings','core']::text[], '{}'::text[], false),
  ('single-leg-glute-bridge', 'Single Leg Glute Bridge', array['one leg glute bridge','single leg bridge','single leg hip thrust']::text[], array['glutes','hamstrings']::text[], '{}'::text[], true),
  ('kettlebell-swing', 'Kettlebell Swing', array['kettlebell swings','kb swing','kb swings','swing','swings','russian swing','american swing','russian kettlebell swing']::text[], array['glutes','hamstrings','back','core']::text[], array['kettlebell']::text[], false),
  ('kettlebell-deadlift', 'Kettlebell Deadlift', array['kb deadlift','suitcase deadlift']::text[], array['glutes','hamstrings','back']::text[], array['kettlebell']::text[], false),
  ('back-extension', 'Back Extension', array['back extensions','hyperextension','hyperextensions','superman machine']::text[], array['back','glutes','hamstrings']::text[], array['machine']::text[], false),
  ('reverse-hyper', 'Reverse Hyper', array['reverse hypers','reverse hyperextension']::text[], array['glutes','hamstrings','back']::text[], array['machine']::text[], false),
  ('nordic-curl', 'Nordic Curl', array['nordic hamstring curl','nordics','nordic ham curl']::text[], array['hamstrings']::text[], '{}'::text[], false),
  ('glute-ham-raise', 'Glute Ham Raise', array['glute ham raises','ghr','ghd raise']::text[], array['hamstrings','glutes']::text[], array['machine']::text[], false),
  ('leg-curl', 'Leg Curl', array['leg curls','hamstring curl','lying leg curl','seated leg curl','machine leg curl']::text[], array['hamstrings']::text[], array['machine']::text[], false),
  ('cable-pull-through', 'Cable Pull Through', array['pull through','pull throughs','rope pull through']::text[], array['glutes','hamstrings']::text[], array['cables']::text[], false),
  ('jefferson-curl', 'Jefferson Curl', array['jefferson curls']::text[], array['back','hamstrings']::text[], array['barbell']::text[], false),
  ('power-clean', 'Power Clean', array['power cleans','clean','cleans']::text[], array['quads','glutes','back','shoulders']::text[], array['barbell']::text[], false),
  ('hang-clean', 'Hang Clean', array['hang cleans','hang power clean']::text[], array['quads','glutes','back','shoulders']::text[], array['barbell']::text[], false),
  ('squat-clean', 'Squat Clean', array['squat cleans','full clean']::text[], array['full body']::text[], array['barbell']::text[], false),
  ('clean-and-jerk', 'Clean and Jerk', array['clean jerk','clean and jerks']::text[], array['full body']::text[], array['barbell']::text[], false),
  ('snatch', 'Snatch', array['snatches','barbell snatch','power snatch']::text[], array['full body']::text[], array['barbell']::text[], false),
  ('push-jerk', 'Push Jerk', array['push jerks']::text[], array['shoulders','triceps','quads']::text[], array['barbell']::text[], false),
  ('split-jerk', 'Split Jerk', array['split jerks']::text[], array['shoulders','quads']::text[], array['barbell']::text[], false),
  ('sumo-deadlift-high-pull', 'Sumo Deadlift High Pull', array['sdhp','sumo dl high pull']::text[], array['full body','shoulders','back']::text[], array['barbell']::text[], false),
  ('kettlebell-clean', 'Kettlebell Clean', array['kettlebell cleans','kb clean']::text[], array['shoulders','back','glutes']::text[], array['kettlebell']::text[], true),
  ('kettlebell-snatch', 'Kettlebell Snatch', array['kettlebell snatches','kb snatch']::text[], array['shoulders','back','glutes']::text[], array['kettlebell']::text[], true),
  ('turkish-get-up', 'Turkish Get Up', array['turkish get ups','turkish getup','tgu','get up']::text[], array['full body','core','shoulders']::text[], array['kettlebell']::text[], true),
  ('bench-press', 'Bench Press', array['bench presses','barbell bench press','bb bench press','flat bench press','flat bench','bench','bp']::text[], array['chest','triceps','shoulders']::text[], array['barbell','bench']::text[], false),
  ('incline-bench-press', 'Incline Bench Press', array['incline bench','incline barbell press','incline barbell bench press']::text[], array['chest','shoulders','triceps']::text[], array['barbell','bench']::text[], false),
  ('decline-bench-press', 'Decline Bench Press', array['decline bench','decline barbell press']::text[], array['chest','triceps']::text[], array['barbell','bench']::text[], false),
  ('close-grip-bench-press', 'Close Grip Bench Press', array['close grip bench','narrow grip bench press','cgbp']::text[], array['triceps','chest']::text[], array['barbell','bench']::text[], false),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', array['db bench press','db bench','dumbbell press','db press','dumbbell chest press','flat dumbbell press']::text[], array['chest','triceps','shoulders']::text[], array['dumbbells','bench']::text[], false),
  ('incline-dumbbell-press', 'Incline Dumbbell Press', array['incline db press','incline dumbbell bench press','incline db bench press']::text[], array['chest','shoulders','triceps']::text[], array['dumbbells','bench']::text[], false),
  ('dumbbell-floor-press', 'Dumbbell Floor Press', array['floor press','db floor press']::text[], array['chest','triceps']::text[], array['dumbbells']::text[], false),
  ('push-up', 'Push-Up', array['push up','push ups','pushup','pushups','press up','press ups','pressups']::text[], array['chest','triceps','shoulders','core']::text[], '{}'::text[], false),
  ('incline-push-up', 'Incline Push-Up', array['incline push ups','incline pushup','elevated push up','hands elevated push up']::text[], array['chest','triceps','shoulders']::text[], array['bench']::text[], false),
  ('decline-push-up', 'Decline Push-Up', array['decline push ups','decline pushup','feet elevated push up']::text[], array['chest','shoulders','triceps']::text[], array['bench']::text[], false),
  ('diamond-push-up', 'Diamond Push-Up', array['diamond pushup','triangle push up','close grip push up','narrow push up']::text[], array['triceps','chest']::text[], '{}'::text[], false),
  ('wide-push-up', 'Wide Push-Up', array['wide grip push up','wide pushup']::text[], array['chest','shoulders']::text[], '{}'::text[], false),
  ('pike-push-up', 'Pike Push-Up', array['pike push ups','pike pushup']::text[], array['shoulders','triceps']::text[], '{}'::text[], false),
  ('archer-push-up', 'Archer Push-Up', array['archer pushup']::text[], array['chest','triceps']::text[], '{}'::text[], true),
  ('plyo-push-up', 'Plyo Push-Up', array['clapping push up','clap push up','explosive push up','plyometric push up']::text[], array['chest','triceps']::text[], '{}'::text[], false),
  ('chest-fly', 'Chest Fly', array['chest flies','dumbbell fly','db fly','dumbbell flyes','flyes','flys','pec fly']::text[], array['chest','shoulders']::text[], array['dumbbells','bench']::text[], false),
  ('incline-dumbbell-fly', 'Incline Dumbbell Fly', array['incline fly','incline flyes','incline db fly']::text[], array['chest','shoulders']::text[], array['dumbbells','bench']::text[], false),
  ('cable-fly', 'Cable Fly', array['cable flies','cable flyes','cable crossover','crossover']::text[], array['chest']::text[], array['cables']::text[], false),
  ('machine-chest-press', 'Machine Chest Press', array['chest press machine','seated chest press','chest press']::text[], array['chest','triceps','shoulders']::text[], array['machine']::text[], false),
  ('pec-deck', 'Pec Deck', array['pec deck fly','butterfly machine','machine fly']::text[], array['chest']::text[], array['machine']::text[], false),
  ('dip', 'Dip', array['dips','parallel bar dip','chest dip','tricep dip','triceps dip','bar dips']::text[], array['triceps','chest','shoulders']::text[], '{}'::text[], false),
  ('ring-dip', 'Ring Dip', array['ring dips']::text[], array['triceps','chest','shoulders']::text[], array['other']::text[], false),
  ('bench-dip', 'Bench Dip', array['bench dips','chair dip']::text[], array['triceps','chest']::text[], array['bench']::text[], false),
  ('landmine-press', 'Landmine Press', array['landmine presses','single arm landmine press']::text[], array['shoulders','chest','triceps']::text[], array['barbell']::text[], true),
  ('svend-press', 'Svend Press', array['plate squeeze press']::text[], array['chest']::text[], array['other']::text[], false),
  ('overhead-press', 'Overhead Press', array['ohp','military press','barbell shoulder press','bb overhead press','strict press','standing press','overhead presses']::text[], array['shoulders','triceps','core']::text[], array['barbell']::text[], false),
  ('seated-shoulder-press', 'Seated Shoulder Press', array['seated overhead press','seated barbell press']::text[], array['shoulders','triceps']::text[], array['barbell','bench']::text[], false),
  ('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', array['shoulder press','shoulder presses','db shoulder press','dumbbell overhead press','db overhead press','seated dumbbell press']::text[], array['shoulders','triceps']::text[], array['dumbbells']::text[], false),
  ('machine-shoulder-press', 'Machine Shoulder Press', array['shoulder press machine','seated machine shoulder press']::text[], array['shoulders','triceps']::text[], array['machine']::text[], false),
  ('arnold-press', 'Arnold Press', array['arnold presses','arnolds']::text[], array['shoulders','triceps']::text[], array['dumbbells']::text[], false),
  ('push-press', 'Push Press', array['push presses']::text[], array['shoulders','triceps','quads']::text[], array['barbell','dumbbells']::text[], false),
  ('handstand-push-up', 'Handstand Push-Up', array['handstand push ups','handstand pushup','hspu']::text[], array['shoulders','triceps']::text[], '{}'::text[], false),
  ('lateral-raise', 'Lateral Raise', array['lateral raises','side raise','side lateral raise','lat raise','db lateral raise','dumbbell lateral raise','cable lateral raise']::text[], array['shoulders']::text[], array['dumbbells','cables']::text[], false),
  ('front-raise', 'Front Raise', array['front raises','dumbbell front raise','db front raise','plate front raise']::text[], array['shoulders']::text[], array['dumbbells']::text[], false),
  ('rear-delt-fly', 'Rear Delt Fly', array['rear delt flies','reverse fly','reverse flyes','rear delt raise','rear fly','bent over rear delt fly']::text[], array['shoulders','back']::text[], array['dumbbells','cables']::text[], false),
  ('upright-row', 'Upright Row', array['upright rows']::text[], array['shoulders','back','forearms']::text[], array['barbell','dumbbells']::text[], false),
  ('face-pull', 'Face Pull', array['face pulls','rope face pull']::text[], array['shoulders','back']::text[], array['cables']::text[], false),
  ('shrug', 'Shrug', array['shrugs','barbell shrug','dumbbell shrug','db shrug','trap shrug']::text[], array['back','forearms']::text[], array['barbell','dumbbells']::text[], false),
  ('band-pull-apart', 'Band Pull Apart', array['band pull aparts','pull aparts']::text[], array['shoulders','back']::text[], array['resistance bands']::text[], false),
  ('arm-circles', 'Arm Circles', array['arm circle','shoulder circles']::text[], array['shoulders']::text[], '{}'::text[], false),
  ('pull-up', 'Pull-Up', array['pull up','pull ups','pullup','pullups','wide grip pull up']::text[], array['back','biceps','forearms']::text[], array['pull-up bar']::text[], false),
  ('chin-up', 'Chin-Up', array['chin up','chin ups','chinup','chinups','underhand pull up']::text[], array['back','biceps']::text[], array['pull-up bar']::text[], false),
  ('assisted-pull-up', 'Assisted Pull-Up', array['assisted pullup','band assisted pull up','machine assisted pull up']::text[], array['back','biceps']::text[], array['pull-up bar','machine']::text[], false),
  ('muscle-up', 'Muscle-Up', array['muscle up','muscle ups','bar muscle up']::text[], array['back','triceps','chest']::text[], array['pull-up bar']::text[], false),
  ('scapular-pull-up', 'Scapular Pull-Up', array['scap pull up','scapular pull ups','scap pulls']::text[], array['back']::text[], array['pull-up bar']::text[], false),
  ('dead-hang', 'Dead Hang', array['dead hangs','bar hang','hang']::text[], array['forearms','back']::text[], array['pull-up bar']::text[], false),
  ('lat-pulldown', 'Lat Pulldown', array['lat pulldowns','lat pull down','pulldown','wide grip pulldown','cable pulldown']::text[], array['back','biceps']::text[], array['cables','machine']::text[], false),
  ('straight-arm-pulldown', 'Straight Arm Pulldown', array['straight arm pull down','lat pushdown']::text[], array['back']::text[], array['cables']::text[], false),
  ('bent-over-row', 'Bent-Over Row', array['bent over row','bent over rows','bentover row','barbell row','barbell rows','bb row','row','rows','pendlay row','bent over barbell row']::text[], array['back','biceps','forearms']::text[], array['barbell']::text[], false),
  ('dumbbell-row', 'Dumbbell Row', array['dumbbell rows','db row','db rows','one arm row','single arm row','single arm dumbbell row','one arm dumbbell row','kroc row','gorilla row']::text[], array['back','biceps']::text[], array['dumbbells','bench']::text[], true),
  ('seated-cable-row', 'Seated Cable Row', array['cable row','cable rows','seated row']::text[], array['back','biceps']::text[], array['cables']::text[], false),
  ('chest-supported-row', 'Chest Supported Row', array['incline row','chest supported dumbbell row','seal row']::text[], array['back','biceps']::text[], array['dumbbells','bench']::text[], false),
  ('t-bar-row', 'T-Bar Row', array['t bar row','tbar row','t bar rows']::text[], array['back','biceps']::text[], array['barbell','machine']::text[], false),
  ('inverted-row', 'Inverted Row', array['inverted rows','body row','bodyweight row','australian pull up','ring row']::text[], array['back','biceps']::text[], array['pull-up bar']::text[], false),
  ('machine-row', 'Machine Row', array['seated machine row','hammer strength row']::text[], array['back','biceps']::text[], array['machine']::text[], false),
  ('renegade-row', 'Renegade Row', array['renegade rows','plank row','push up row']::text[], array['back','core','biceps']::text[], array['dumbbells']::text[], true),
  ('meadows-row', 'Meadows Row', array['landmine row']::text[], array['back','biceps']::text[], array['barbell']::text[], true),
  ('pull-over', 'Pull-Over', array['pullover','pullovers','dumbbell pullover','db pullover','lat pullover']::text[], array['back','chest']::text[], array['dumbbells']::text[], false),
  ('high-pull', 'High Pull', array['barbell high pull','kettlebell high pull']::text[], array['shoulders','back']::text[], array['barbell','kettlebell']::text[], false),
  ('farmers-carry', 'Farmer''s Carry', array['farmers carry','farmers walk','farmer carry','suitcase carry','loaded carry']::text[], array['forearms','core','back']::text[], array['dumbbells','kettlebell']::text[], false),
  ('overhead-carry', 'Overhead Carry', array['overhead carries','waiter carry','overhead walk']::text[], array['shoulders','core']::text[], array['kettlebell','dumbbells']::text[], false),
  ('dumbbell-curl', 'Dumbbell Curl', array['dumbbell curls','curl','curls','bicep curl','bicep curls','biceps curl','db curl','standing dumbbell curl']::text[], array['biceps','forearms']::text[], array['dumbbells']::text[], false),
  ('barbell-curl', 'Barbell Curl', array['barbell curls','bb curl','straight bar curl']::text[], array['biceps','forearms']::text[], array['barbell']::text[], false),
  ('ez-bar-curl', 'EZ Bar Curl', array['ez curl','ez bar curls']::text[], array['biceps','forearms']::text[], array['barbell']::text[], false),
  ('hammer-curl', 'Hammer Curl', array['hammer curls','db hammer curl','neutral grip curl']::text[], array['biceps','forearms']::text[], array['dumbbells']::text[], false),
  ('preacher-curl', 'Preacher Curl', array['preacher curls','scott curl']::text[], array['biceps']::text[], array['barbell','bench']::text[], false),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', array['incline curl','incline db curl']::text[], array['biceps']::text[], array['dumbbells','bench']::text[], false),
  ('concentration-curl', 'Concentration Curl', array['concentration curls']::text[], array['biceps']::text[], array['dumbbells']::text[], true),
  ('cable-curl', 'Cable Curl', array['cable curls','cable bicep curl','rope curl']::text[], array['biceps']::text[], array['cables']::text[], false),
  ('spider-curl', 'Spider Curl', array['spider curls']::text[], array['biceps']::text[], array['dumbbells','bench']::text[], false),
  ('zottman-curl', 'Zottman Curl', array['zottman curls']::text[], array['biceps','forearms']::text[], array['dumbbells']::text[], false),
  ('drag-curl', 'Drag Curl', array['drag curls']::text[], array['biceps']::text[], array['barbell']::text[], false),
  ('reverse-curl', 'Reverse Curl', array['reverse curls','reverse grip curl']::text[], array['forearms','biceps']::text[], array['barbell','dumbbells']::text[], false),
  ('wrist-curl', 'Wrist Curl', array['wrist curls','forearm curl']::text[], array['forearms']::text[], array['dumbbells','barbell']::text[], false),
  ('tricep-pushdown', 'Tricep Pushdown', array['tricep pushdowns','triceps pushdown','pushdown','rope pushdown','cable pushdown','tricep push down']::text[], array['triceps']::text[], array['cables']::text[], false),
  ('overhead-tricep-extension', 'Overhead Tricep Extension', array['overhead triceps extension','tricep extension','triceps extension','french press','overhead extension']::text[], array['triceps']::text[], array['dumbbells','cables']::text[], false),
  ('skull-crusher', 'Skull Crusher', array['skull crushers','skullcrusher','lying tricep extension','lying triceps extension']::text[], array['triceps']::text[], array['barbell','bench']::text[], false),
  ('tricep-kickback', 'Tricep Kickback', array['tricep kickbacks','triceps kickback','db kickback']::text[], array['triceps']::text[], array['dumbbells']::text[], true),
  ('plank', 'Plank', array['planks','forearm plank','front plank','plank hold','high plank','elbow plank']::text[], array['core','shoulders']::text[], '{}'::text[], false),
  ('side-plank', 'Side Plank', array['side planks','side plank hold']::text[], array['core']::text[], '{}'::text[], true),
  ('copenhagen-plank', 'Copenhagen Plank', array['copenhagen','copenhagen side plank']::text[], array['core']::text[], array['bench']::text[], true),
  ('plank-shoulder-tap', 'Plank Shoulder Tap', array['shoulder taps','plank shoulder taps','shoulder tap']::text[], array['core','shoulders']::text[], '{}'::text[], false),
  ('hip-dip', 'Hip Dip', array['hip dips','plank hip dip','side plank hip dip']::text[], array['core']::text[], '{}'::text[], false),
  ('crunch', 'Crunch', array['crunches','ab crunch','abdominal crunch']::text[], array['core']::text[], '{}'::text[], false),
  ('reverse-crunch', 'Reverse Crunch', array['reverse crunches']::text[], array['core']::text[], '{}'::text[], false),
  ('cable-crunch', 'Cable Crunch', array['kneeling cable crunch','rope crunch']::text[], array['core']::text[], array['cables']::text[], false),
  ('sit-up', 'Sit-Up', array['sit up','sit ups','situp','situps','full sit up']::text[], array['core']::text[], '{}'::text[], false),
  ('bicycle-crunch', 'Bicycle Crunch', array['bicycle crunches','bicycles','bicycle kicks']::text[], array['core']::text[], '{}'::text[], false),
  ('russian-twist', 'Russian Twist', array['russian twists','seated twist']::text[], array['core']::text[], array['medicine ball']::text[], false),
  ('leg-raise', 'Leg Raise', array['leg raises','lying leg raise','lying leg raises']::text[], array['core']::text[], '{}'::text[], false),
  ('hanging-leg-raise', 'Hanging Leg Raise', array['hanging leg raises','hanging leg lift']::text[], array['core','forearms']::text[], array['pull-up bar']::text[], false),
  ('hanging-knee-raise', 'Hanging Knee Raise', array['hanging knee raises','knee raise','knee raises']::text[], array['core','forearms']::text[], array['pull-up bar']::text[], false),
  ('toes-to-bar', 'Toes to Bar', array['toes to bars','ttb','t2b','toes 2 bar']::text[], array['core','forearms','back']::text[], array['pull-up bar']::text[], false),
  ('v-up', 'V-Up', array['v up','v ups','vups','v sit up']::text[], array['core']::text[], '{}'::text[], false),
  ('hollow-hold', 'Hollow Hold', array['hollow holds','hollow body hold','hollow rock','hollow rocks']::text[], array['core']::text[], '{}'::text[], false),
  ('dead-bug', 'Dead Bug', array['dead bugs','deadbug']::text[], array['core']::text[], '{}'::text[], false),
  ('bird-dog', 'Bird Dog', array['bird dogs','birddog']::text[], array['core','back','glutes']::text[], '{}'::text[], true),
  ('mountain-climber', 'Mountain Climber', array['mountain climbers','mtn climbers']::text[], array['core','shoulders','full body']::text[], '{}'::text[], false),
  ('flutter-kick', 'Flutter Kick', array['flutter kicks']::text[], array['core']::text[], '{}'::text[], false),
  ('scissor-kick', 'Scissor Kick', array['scissor kicks']::text[], array['core']::text[], '{}'::text[], false),
  ('heel-tap', 'Heel Tap', array['heel taps','lying heel tap']::text[], array['core']::text[], '{}'::text[], false),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', array['ab rollout','ab wheel','rollout','barbell rollout','ab roller']::text[], array['core']::text[], array['other']::text[], false),
  ('sit-through', 'Sit Through', array['sit throughs','bear sit through']::text[], array['core','full body']::text[], '{}'::text[], false),
  ('windshield-wiper', 'Windshield Wiper', array['windshield wipers']::text[], array['core']::text[], '{}'::text[], false),
  ('superman', 'Superman', array['supermans','supermen','superman hold']::text[], array['back','glutes']::text[], '{}'::text[], false),
  ('pallof-press', 'Pallof Press', array['pallof presses','anti rotation press']::text[], array['core']::text[], array['cables','resistance bands']::text[], false),
  ('dragon-flag', 'Dragon Flag', array['dragon flags']::text[], array['core']::text[], array['bench']::text[], false),
  ('l-sit', 'L-Sit', array['l sit','l sits','l sit hold']::text[], array['core','triceps']::text[], '{}'::text[], false),
  ('side-bend', 'Side Bend', array['side bends','dumbbell side bend','oblique side bend']::text[], array['core']::text[], array['dumbbells']::text[], true),
  ('woodchop', 'Woodchop', array['woodchops','wood chop','cable woodchop','chop']::text[], array['core']::text[], array['cables']::text[], true),
  ('landmine-rotation', 'Landmine Rotation', array['landmine rotations','landmine twist']::text[], array['core','shoulders']::text[], array['barbell']::text[], false),
  ('bear-crawl', 'Bear Crawl', array['bear crawls']::text[], array['core','shoulders','full body']::text[], '{}'::text[], false),
  ('kettlebell-windmill', 'Kettlebell Windmill', array['windmill','windmills','kb windmill']::text[], array['core','shoulders']::text[], array['kettlebell']::text[], true),
  ('kettlebell-halo', 'Kettlebell Halo', array['halo','halos','kb halo']::text[], array['shoulders','core']::text[], array['kettlebell']::text[], false),
  ('running', 'Running', array['run','runs','jog','jogs','jogging','steady state run']::text[], array['full body','calves']::text[], '{}'::text[], false),
  ('sprint', 'Sprint', array['sprints','sprint intervals','hill sprint']::text[], array['full body','quads']::text[], '{}'::text[], false),
  ('treadmill-run', 'Treadmill Run', array['treadmill','treadmill running','incline treadmill walk']::text[], array['full body','calves']::text[], array['machine']::text[], false),
  ('cycling', 'Cycling', array['bike','biking','cycle','stationary bike','spin bike']::text[], array['quads','calves','full body']::text[], array['machine']::text[], false),
  ('assault-bike', 'Assault Bike', array['air bike','echo bike','fan bike']::text[], array['full body']::text[], array['machine']::text[], false),
  ('rowing-machine', 'Rowing Machine', array['rowing','indoor rowing','row erg','rower','erg','concept 2']::text[], array['full body','back']::text[], array['machine']::text[], false),
  ('ski-erg', 'Ski Erg', array['skierg','ski machine']::text[], array['full body','back']::text[], array['machine']::text[], false),
  ('stair-climber', 'Stair Climber', array['stairmaster','stair master','stair stepper','stairs']::text[], array['glutes','quads','calves']::text[], array['machine']::text[], false),
  ('elliptical', 'Elliptical', array['cross trainer','elliptical machine']::text[], array['full body']::text[], array['machine']::text[], false),
  ('jump-rope', 'Jump Rope', array['jump ropes','skipping','skipping rope','rope skipping']::text[], array['calves','full body']::text[], array['jump rope']::text[], false),
  ('double-under', 'Double Under', array['double unders','dubs']::text[], array['calves','full body']::text[], array['jump rope']::text[], false),
  ('burpee', 'Burpee', array['burpees','burpee to jump']::text[], array['full body']::text[], '{}'::text[], false),
  ('devils-press', 'Devil''s Press', array['devils press','devil press']::text[], array['full body']::text[], array['dumbbells']::text[], false),
  ('man-maker', 'Man Maker', array['man makers','manmaker']::text[], array['full body']::text[], array['dumbbells']::text[], false),
  ('jumping-jack', 'Jumping Jack', array['jumping jacks','star jump','star jumps']::text[], array['full body','calves']::text[], '{}'::text[], false),
  ('high-knees', 'High Knees', array['high knee','running in place high knees']::text[], array['quads','calves','core']::text[], '{}'::text[], false),
  ('butt-kicks', 'Butt Kicks', array['butt kickers','heel kicks']::text[], array['hamstrings','calves']::text[], '{}'::text[], false),
  ('battle-ropes', 'Battle Ropes', array['battle rope','battling ropes','rope slams']::text[], array['shoulders','core','full body']::text[], array['other']::text[], false),
  ('sled-push', 'Sled Push', array['sled pushes','prowler push']::text[], array['quads','glutes','full body']::text[], array['other']::text[], false),
  ('sled-pull', 'Sled Pull', array['sled pulls','sled drag']::text[], array['back','hamstrings','full body']::text[], array['other']::text[], false),
  ('shuttle-run', 'Shuttle Run', array['shuttle runs','suicides','line drill']::text[], array['full body','quads']::text[], '{}'::text[], false),
  ('medicine-ball-slam', 'Medicine Ball Slam', array['medicine ball slams','ball slam','med ball slam','slam ball','slams']::text[], array['full body','core','shoulders']::text[], array['medicine ball']::text[], false),
  ('wall-walk', 'Wall Walk', array['wall walks']::text[], array['shoulders','core']::text[], '{}'::text[], false),
  ('inchworm', 'Inchworm', array['inchworms','inch worm','walkout','inchworm walkout']::text[], array['full body','core','hamstrings']::text[], '{}'::text[], false),
  ('hip-abduction', 'Hip Abduction', array['abduction machine','hip abductor','seated hip abduction']::text[], array['glutes']::text[], array['machine']::text[], false),
  ('hip-adduction', 'Hip Adduction', array['adduction machine','hip adductor','seated hip adduction']::text[], array['quads']::text[], array['machine']::text[], false),
  ('clamshell', 'Clamshell', array['clamshells','clam shell','banded clamshell']::text[], array['glutes']::text[], array['resistance bands']::text[], true),
  ('fire-hydrant', 'Fire Hydrant', array['fire hydrants']::text[], array['glutes']::text[], '{}'::text[], true),
  ('donkey-kick', 'Donkey Kick', array['donkey kicks','glute kickback','glute kickbacks','cable kickback']::text[], array['glutes']::text[], '{}'::text[], true),
  ('banded-walk', 'Banded Walk', array['banded walks','monster walk','lateral band walk','banded lateral walk']::text[], array['glutes']::text[], array['resistance bands']::text[], false),
  ('frog-pump', 'Frog Pump', array['frog pumps']::text[], array['glutes']::text[], '{}'::text[], false),
  ('side-lying-leg-raise', 'Side Lying Leg Raise', array['side leg raise','side lying leg lifts','lying side leg lift']::text[], array['glutes']::text[], '{}'::text[], true),
  ('leg-swing', 'Leg Swing', array['leg swings']::text[], array['hamstrings','glutes']::text[], '{}'::text[], true),
  ('hip-circle', 'Hip Circle', array['hip circles']::text[], array['glutes']::text[], '{}'::text[], false),
  ('downward-dog', 'Downward Dog', array['downward facing dog','down dog','adho mukha svanasana']::text[], array['shoulders','hamstrings','calves']::text[], '{}'::text[], false),
  ('childs-pose', 'Child''s Pose', array['childs pose','child pose','balasana']::text[], array['back']::text[], '{}'::text[], false),
  ('cat-cow', 'Cat-Cow', array['cat cow','cat camel','cat cow stretch']::text[], array['back','core']::text[], '{}'::text[], false),
  ('cobra-stretch', 'Cobra Stretch', array['cobra pose','cobra','upward dog','upward facing dog']::text[], array['back','core']::text[], '{}'::text[], false),
  ('pigeon-pose', 'Pigeon Pose', array['pigeon stretch','pigeon']::text[], array['glutes']::text[], '{}'::text[], false),
  ('hip-flexor-stretch', 'Hip Flexor Stretch', array['hip flexor stretches','couch stretch','kneeling hip flexor stretch']::text[], array['quads','glutes']::text[], '{}'::text[], true),
  ('hamstring-stretch', 'Hamstring Stretch', array['seated hamstring stretch','standing hamstring stretch']::text[], array['hamstrings']::text[], '{}'::text[], false),
  ('worlds-greatest-stretch', 'World''s Greatest Stretch', array['worlds greatest stretch','greatest stretch','wgs']::text[], array['full body']::text[], '{}'::text[], true),
  ('thread-the-needle', 'Thread the Needle', array['thread needle','thread the needle stretch']::text[], array['back','shoulders']::text[], '{}'::text[], true),
  ('sun-salutation', 'Sun Salutation', array['sun salutations','surya namaskar']::text[], array['full body']::text[], '{}'::text[], false)
on conflict (id) do update set
  display_name  = excluded.display_name,
  aliases       = excluded.aliases,
  muscle_groups = excluded.muscle_groups,
  equipment     = excluded.equipment,
  unilateral    = excluded.unilateral,
  updated_at    = now();
